import json

with open('../data/risk_data.json') as f:
    data = json.load(f)

mini = json.dumps(data, separators=(',', ':'))

with open('../js/data.js', 'w') as f:
    f.write('/* ========================================\n')
    f.write('   RiskMapper Nepal - data.js\n')
    f.write('   REAL DATA: NPC/CBS/KLL 2015 Survey + USGS ShakeMap + Vs30 Soil\n')
    f.write('   Generated by build_real_scores.py from 260,601 building records\n')
    f.write('   ======================================== */\n\n')
    f.write('const RISK_DATA = ' + mini + ';\n\n')
    f.write("const LEVEL_COLORS = { critical: '#e02020', high: '#f47a1f', moderate: '#f0b429', low: '#2ab96e' };\n")
    f.write("const LEVEL_LABELS = { critical: 'CRITICAL', high: 'HIGH', moderate: 'MOD', low: 'LOW' };\n")

print(f'data.js written: {len(mini)} chars')
